namespace CodeHarness.Desktop.Controls
{
	[default_interface]
	runtimeclass Sidebar : Microsoft.UI.Xaml.Controls.UserControl
	{
		Sidebar();

		void SetSessions(Windows.Foundation.Collections.IVectorView<String> sessions);
		void SetWorkdir(String workdir);
		void Focus();
	}
}
